### ISSUE TITLE
У тебя проблема с добавлением пользователей!

### ISSUE THREAD

**Issue by PoryvaevAM** [VladSerdobintsev/SpringShop#1]
Не добавляются пользователи.

Шаги для воспроизведения проблемы:
1) Запускаем приложение
2) Заходим под админом
3) Переходим в профиль
4) Переходим по ссылке >>Добавить пользователя
5) Заполняем форму и нажимаем кнопку Добавить пользователя

Ожидаемый результат:
Пользователь добавляется в список.

Фактический результат:
Пользователь не добавляется в список.

**Comment by VladSerdobintsev** [comment]
Я пофиксил данный баг.
