### ISSUE TITLE
Проблема отредактировать данные пользователя!

### ISSUE THREAD

**Issue by PoryvaevAM** [VladSerdobintsev/SpringShop#2]
Не редактируются данные пользователя.

Шаги для воспроизведения проблемы:
1) Запускаем приложение
2) Заходим под админом
3) Переходим в профиль
4) Переходим по ссылке >>Редактировать пользователя
5) Изменяем данные в  форме и нажимаем кнопку Сохранить

Ожидаемый результат:
Получаем пользователя с измененными данными.

Фактический результат:
Пользователь остается без изменений.

**Comment by VladSerdobintsev** [comment]
Я пофиксил данный баг.
