### ISSUE TITLE
Есть проблема при оформлении заказа!

### ISSUE THREAD

**Issue by PoryvaevAM** [VladSerdobintsev/SpringShop#3]
При попытке оформить заказ выбрасывает на левую страницу.

Шаги для воспроизведения проблемы:
1) Запускаем приложение
2) Заходим под админом
3) Переходим в Просмотр категорий
4) Выбираем категорию например electronic.
5) Выбираем товар и Добавляем в корзину.
6) Нажимаем заказать.
7) Вводим адрес доставки и нажимаем заказать.

Ожидаемый результат:
Переход на главную страницу.

Фактический результат:
Чистая страница с возможностью добавлять список групп товаров.

**Comment by VladSerdobintsev** [comment]
Изменил страницу, на которую происходит перенаправление.
